// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReActor = require("../../src/ReActor.bs.js");

function loop(_env, state) {
  ReActor.$less$neg(state[/* target */0], state[/* message */1]);
  return /* OnAnimationFrame */Block.__(1, [state]);
}

function start(param) {
  return ReActor.spawn(loop, param);
}

exports.loop = loop;
exports.start = start;
/* ReActor Not a pure module */
