// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE


function worker_type_to_string() {
  return "module";
}

var FFI = /* module */[];

function make(src, _) {
  return new Worker(src, {
              type: "module"
            });
}

function onMessage(handler, worker) {
  worker.onmessage = handler;
  return worker;
}

function postMessage(message, worker) {
  worker.postMessage(message);
  return /* () */0;
}

export {
  worker_type_to_string ,
  FFI ,
  make ,
  onMessage ,
  postMessage ,
  
}
/* No side effect */
