// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE


var hardwareConcurrency = self.navigator.hardwareConcurrency;

export {
  hardwareConcurrency ,
  
}
/* hardwareConcurrency Not a pure module */
