// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE


function defer(prim, prim$1) {
  setTimeout(prim, prim$1);
  return /* () */0;
}

function nextTick(prim) {
  setImmediate(prim);
  return /* () */0;
}

export {
  defer ,
  nextTick ,
  
}
/* No side effect */
