// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as FFI_Window$Reactor from "./FFI_Window.bs.js";
import * as ReActor_Node$Reactor from "./ReActor_Node.bs.js";

var main = ReActor_Node$Reactor.run(ReActor_Node$Reactor.make(500, FFI_Window$Reactor.hardwareConcurrency - 1 | 0));

console.log("Created main scheduler...");

function spawn(param) {
  return ReActor_Node$Reactor.spawn(main, param);
}

export {
  main ,
  spawn ,
  
}
/* main Not a pure module */
