// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as ReActor_Node$Reactor from "./ReActor_Node.bs.js";

var __main = ReActor_Node$Reactor.make(/* () */0);

console.log("Created main scheduler...");

console.log(__main);

function spawn(f, args) {
  return ReActor_Node$Reactor.spawn(__main, f, args);
}

var Process = 0;

export {
  Process ,
  __main ,
  spawn ,
  
}
/* __main Not a pure module */
