// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as ReActor_Node from "./ReActor_Node.bs.js";

var __main = ReActor_Node.make(/* () */0);

function spawn(f, args) {
  return ReActor_Node.spawn(__main, f, args);
}

function exit(param) {
  return ReActor_Node.exit(__main, param);
}

function register(param, param$1) {
  return ReActor_Node.register(__main, param, param$1);
}

function whereIs(param) {
  return ReActor_Node.whereIs(__main, param);
}

function send(param, param$1) {
  return ReActor_Node.send(__main, param, param$1);
}

function trace(param) {
  return ReActor_Node.trace(__main, param);
}

var Runtime = 0;

var Node = 0;

var Scheduler = 0;

var Sid = 0;

var Process = 0;

var Pid = 0;

var Message = 0;

var Tracer = 0;

export {
  Runtime ,
  Node ,
  Scheduler ,
  Sid ,
  Process ,
  Pid ,
  Message ,
  Tracer ,
  __main ,
  spawn ,
  exit ,
  register ,
  whereIs ,
  send ,
  trace ,
  
}
/* __main Not a pure module */
