// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Curry from "../../../node_modules/bs-platform/lib/es6/curry.js";
import * as Caml_obj from "../../../node_modules/bs-platform/lib/es6/caml_obj.js";
import * as FFI_Runtime$Reactor from "./FFI_Runtime.bs.js";

function make(node_name, scheduler_id, process_number) {
  return /* tuple */[
          node_name,
          scheduler_id,
          process_number
        ];
}

var Pid = /* module */[/* make */make];

function make$1(pid, f, initial_args) {
  var process_003 = /* status : record */[/* contents : Dead */1];
  var $$process = /* record */[
    /* pid */pid,
    /* f */f,
    /* initial_args */initial_args,
    process_003
  ];
  var env = [];
  var run = function (args) {
    var args$prime = Curry._2(f, env, args);
    var match = process_003[0];
    if (match) {
      return /* () */0;
    } else {
      return FFI_Runtime$Reactor.defer((function () {
                    return run(args$prime);
                  }), 0);
    }
  };
  Caml_obj.caml_update_dummy(env, /* record */[
        /* self */(function () {
            return pid;
          }),
        /* loop */(function (args) {
            FFI_Runtime$Reactor.defer((function () {
                    return run(args);
                  }), 0);
            return args;
          })
      ]);
  run(initial_args);
  return $$process;
}

export {
  Pid ,
  make$1 as make,
  
}
/* No side effect */
