// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Curry from "../../../node_modules/bs-platform/lib/es6/curry.js";

function trace(tracer, pid, message) {
  var match = Curry._2(tracer[/* matcher */0], pid, message);
  if (match) {
    return Curry._1(tracer[/* handler */1], message);
  } else {
    return /* () */0;
  }
}

export {
  trace ,
  
}
/* No side effect */
