// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE


function pid(node, proc_count, noise) {
  return /* tuple */[
          node,
          proc_count,
          noise
        ];
}

function mfa(m, f, _, a) {
  return /* tuple */[
          m,
          f,
          a
        ];
}

export {
  pid ,
  mfa ,
  
}
/* No side effect */
