// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as List from "../../../node_modules/bs-platform/lib/es6/list.js";
import * as ReActor_Utils$Reactor from "./ReActor_Utils.bs.js";
import * as ReActor_Process$Reactor from "./ReActor_Process.bs.js";

function nextPid(param) {
  var match = param[/* id */0];
  return ReActor_Process$Reactor.Pid[/* make */0](match[0], match[1], param[/* process_count */1] + 1 | 0);
}

function leastBusy(workers) {
  return List.nth(workers, 0);
}

function make(node_name) {
  return /* record */[
          /* id : tuple */[
            node_name,
            ReActor_Utils$Reactor.Random[/* shortId */3](/* () */0)
          ],
          /* process_count */0
        ];
}

function spawn(f, args, scheduler) {
  var pid = nextPid(scheduler[0]);
  ReActor_Process$Reactor.make(pid, f, args);
  var init = scheduler[0];
  var scheduler$prime_000 = /* id */init[/* id */0];
  var scheduler$prime_001 = /* process_count */scheduler[0][/* process_count */1] + 1 | 0;
  var scheduler$prime = /* record */[
    scheduler$prime_000,
    scheduler$prime_001
  ];
  scheduler[0] = scheduler$prime;
  return pid;
}

export {
  nextPid ,
  leastBusy ,
  make ,
  spawn ,
  
}
/* No side effect */
