// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as List from "../../../node_modules/bs-platform/lib/es6/list.js";
import * as $$Array from "../../../node_modules/bs-platform/lib/es6/array.js";
import * as Curry from "../../../node_modules/bs-platform/lib/es6/curry.js";
import * as Caml_array from "../../../node_modules/bs-platform/lib/es6/caml_array.js";
import * as ReActor$Reactor from "./ReActor.bs.js";

function noop(env, state) {
  return Curry._1(env[/* loop */1], /* record */[/* counter */state[/* counter */0] + 1 | 0]);
}

var pids = List.map((function (i) {
        return ReActor$Reactor.spawn(noop, /* record */[/* counter */i]);
      }), $$Array.to_list(Caml_array.caml_make_vect(1000000, 0)));

export {
  noop ,
  pids ,
  
}
/* pids Not a pure module */
