// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as ReActor$Reactor from "./ReActor.bs.js";
import * as FFI_Runtime$Reactor from "./FFI_Runtime.bs.js";

function f(a, b) {
  var c = a + b | 0;
  console.log("" + (String(a) + (" + " + (String(b) + (" = " + (String(c) + ""))))));
  return /* () */0;
}

function run() {
  console.log(ReActor$Reactor.spawn(/* () */0));
  return /* () */0;
}

console.log(ReActor$Reactor.spawn(/* () */0));

FFI_Runtime$Reactor.defer((function () {
        console.log(ReActor$Reactor.spawn(/* () */0));
        return /* () */0;
      }), 1000);

FFI_Runtime$Reactor.defer((function () {
        console.log(ReActor$Reactor.spawn(/* () */0));
        return /* () */0;
      }), 1000);

FFI_Runtime$Reactor.defer((function () {
        console.log(ReActor$Reactor.spawn(/* () */0));
        return /* () */0;
      }), 1000);

FFI_Runtime$Reactor.defer((function () {
        console.log(ReActor$Reactor.spawn(/* () */0));
        return /* () */0;
      }), 1000);

FFI_Runtime$Reactor.defer((function () {
        console.log(ReActor$Reactor.spawn(/* () */0));
        return /* () */0;
      }), 1000);

export {
  f ,
  run ,
  
}
/*  Not a pure module */
