// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Curry from "../../../node_modules/bs-platform/lib/es6/curry.js";
import * as ReActor$Reactor from "./ReActor.bs.js";

function noop(env, state) {
  return Curry._1(env[/* loop */1], /* record */[/* counter */state[/* counter */0] + 1 | 0]);
}

var pids_000 = ReActor$Reactor.spawn(noop, /* record */[/* counter */0]);

var pids_001 = /* :: */[
  ReActor$Reactor.spawn(noop, /* record */[/* counter */0]),
  /* :: */[
    ReActor$Reactor.spawn(noop, /* record */[/* counter */0]),
    /* :: */[
      ReActor$Reactor.spawn(noop, /* record */[/* counter */0]),
      /* [] */0
    ]
  ]
];

var pids = /* :: */[
  pids_000,
  pids_001
];

export {
  noop ,
  pids ,
  
}
/* pids Not a pure module */
