// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as List from "../../../../node_modules/bs-platform/lib/es6/list.js";
import * as Block from "../../../../node_modules/bs-platform/lib/es6/block.js";
import * as Curry from "../../../../node_modules/bs-platform/lib/es6/curry.js";
import * as Option from "./Option.bs.js";
import * as ReActor from "../../src/ReActor.bs.js";
import * as Game_FFI from "./Game_FFI.bs.js";
import * as EventHandler from "./EventHandler.bs.js";
import * as Game_Renderer from "./Game_Renderer.bs.js";
import * as ReActor_Utils from "../../src/ReActor_Utils.bs.js";
import * as Game_DebugInfo from "./Game_DebugInfo.bs.js";
import * as Caml_exceptions from "../../../../node_modules/bs-platform/lib/es6/caml_exceptions.js";

var Move = Caml_exceptions.create("Main.Cursor.Move");

var Click = Caml_exceptions.create("Main.Cursor.Click");

function handleMessage(state, message) {
  if (message[0] === Move) {
    return /* record */[
            /* x */message[1],
            /* y */message[2],
            /* status : Normal */1
          ];
  } else if (message[0] === Click) {
    return /* record */[
            /* x */message[1],
            /* y */message[2],
            /* status : Click */0
          ];
  } else {
    return state;
  }
}

function render(param) {
  var y = param[/* y */1];
  var x = param[/* x */0];
  Option.$great$great$pipe(ReActor.whereIs(Game_Renderer.name), (function (pid) {
          return ReActor.send(pid, [
                      Game_Renderer.Pipeline,
                      /* :: */[
                        /* DrawCircle */Block.__(1, [
                            /* Point2D */[
                              x,
                              y
                            ],
                            10,
                            /* RGBA */Block.__(2, [
                                255,
                                255,
                                255,
                                0.7
                              ])
                          ]),
                        /* [] */0
                      ]
                    ]);
        }));
  return /* () */0;
}

function loop(env, state) {
  var state$prime = Option.$less$pipe$great(Option.$great$great$pipe(Curry._1(env[/* recv */1], /* () */0), (function (param) {
              return handleMessage(state, param);
            })), state);
  var match = state$prime[/* status */2];
  if (!match) {
    render(state$prime);
  }
  return /* Become */Block.__(0, [state$prime]);
}

function start() {
  return ReActor.spawn(loop, /* record */[
              /* x */0,
              /* y */0,
              /* status : Normal */1
            ]);
}

var Cursor = /* module */[
  /* Move */Move,
  /* Click */Click,
  /* handleMessage */handleMessage,
  /* render */render,
  /* loop */loop,
  /* start */start
];

function repaint(surface, color) {
  Option.$great$great$pipe(ReActor.whereIs(Game_Renderer.name), (function (pid) {
          return ReActor.send(pid, [
                      Game_Renderer.Pipeline,
                      /* :: */[
                        /* DrawRect */Block.__(3, [
                            surface,
                            color
                          ]),
                        /* [] */0
                      ]
                    ]);
        }));
  return /* () */0;
}

var events = /* :: */[
  /* Click */3,
  /* :: */[
    /* MouseMove */4,
    /* :: */[
      /* KeyDown */1,
      /* :: */[
        /* Resize */2,
        /* [] */0
      ]
    ]
  ]
];

function registerEvents(self) {
  Option.$great$great$pipe(ReActor.whereIs(EventHandler.name), (function (pid) {
          return List.iter((function (param) {
                        return ReActor.send(pid, param);
                      }), List.map((function (e) {
                            return [
                                    EventHandler.Subscribe,
                                    e,
                                    self
                                  ];
                          }), events));
        }));
  return /* () */0;
}

function setup(env, state) {
  repaint(state[/* surface */3], state[/* color */2]);
  registerEvents(Curry._1(env[/* self */0], /* () */0));
  return /* Become */Block.__(0, [/* record */[
              /* status : Started */1,
              /* cursor */state[/* cursor */1],
              /* color */state[/* color */2],
              /* surface */state[/* surface */3]
            ]]);
}

function handleEvent(state, $$event) {
  Game_DebugInfo.report($$event);
  if (typeof $$event === "number") {
    return /* Become */Block.__(0, [state]);
  } else {
    switch ($$event.tag | 0) {
      case 0 : 
          return /* Become */Block.__(0, [state]);
      case 1 : 
          ReActor.send(state[/* cursor */1], [
                Click,
                $$event[0],
                $$event[1]
              ]);
          return /* Become */Block.__(0, [state]);
      case 2 : 
          ReActor.send(state[/* cursor */1], [
                Move,
                $$event[0],
                $$event[1]
              ]);
          return /* Become */Block.__(0, [state]);
      case 3 : 
          var state$prime_000 = /* status */state[/* status */0];
          var state$prime_001 = /* cursor */state[/* cursor */1];
          var state$prime_002 = /* color */state[/* color */2];
          var state$prime_003 = /* surface : Rect */[
            0,
            0,
            $$event[0],
            $$event[1]
          ];
          var state$prime = /* record */[
            state$prime_000,
            state$prime_001,
            state$prime_002,
            state$prime_003
          ];
          repaint(state$prime_003, state$prime_002);
          return /* Become */Block.__(0, [state$prime]);
      
    }
  }
}

function handleMessage$1(state, param) {
  if (param[0] === EventHandler.Event) {
    return handleEvent(state, param[1]);
  } else {
    return /* Become */Block.__(0, [state]);
  }
}

function loop$1(env, state) {
  var match = state[/* status */0];
  if (match) {
    return Option.$less$pipe$great(Option.$great$great$pipe(Curry._1(env[/* recv */1], /* () */0), (function (param) {
                      return handleMessage$1(state, param);
                    })), /* Become */Block.__(0, [state]));
  } else {
    return setup(env, state);
  }
}

function start$1() {
  return ReActor.spawn(loop$1, /* record */[
              /* status : ShouldSetup */0,
              /* cursor */start(/* () */0),
              /* color : Hex */Block.__(0, [3556687]),
              /* surface : Rect */[
                0,
                0,
                Game_FFI.Viewport[/* width */0](/* () */0),
                Game_FFI.Viewport[/* height */1](/* () */0)
              ]
            ]);
}

var Scene = /* module */[
  /* repaint */repaint,
  /* events */events,
  /* registerEvents */registerEvents,
  /* setup */setup,
  /* handleEvent */handleEvent,
  /* handleMessage */handleMessage$1,
  /* loop */loop$1,
  /* start */start$1
];

function start$2() {
  Game_DebugInfo.start(/* () */0);
  EventHandler.start(/* () */0);
  Game_Renderer.start(/* () */0);
  start$1(/* () */0);
  return /* () */0;
}

var Game = /* module */[/* start */start$2];

ReActor.trace(/* record */[
      /* matcher */(function (_, _$1) {
          return true;
        }),
      /* handler */(function (e) {
          console.log(ReActor_Utils.$$Date[/* now */0](/* () */0), e);
          return /* () */0;
        }),
      /* timeout */705032704
    ]);

start$2(/* () */0);

export {
  Cursor ,
  Scene ,
  Game ,
  
}
/*  Not a pure module */
