// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Curry from "../../../../node_modules/bs-platform/lib/es6/curry.js";
import * as Js_primitive from "../../../../node_modules/bs-platform/lib/es6/js_primitive.js";

function $great$great$pipe(o, f) {
  if (o !== undefined) {
    return Js_primitive.some(Curry._1(f, Js_primitive.valFromOption(o)));
  }
  
}

function $less$pipe$great(a, b) {
  if (a !== undefined) {
    return Js_primitive.valFromOption(a);
  } else {
    return b;
  }
}

export {
  $great$great$pipe ,
  $less$pipe$great ,
  
}
/* No side effect */
