// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var Window = 0;

var Runtime = 0;

var WebWorker = 0;

exports.Window = Window;
exports.Runtime = Runtime;
exports.WebWorker = WebWorker;
/* No side effect */
