// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var ReActor_Runtime = require("./ReActor_Runtime.bs.js");

var Message = /* module */[];

function make(node_name, scheduler_id, process_number) {
  return /* tuple */[
          node_name,
          scheduler_id,
          process_number
        ];
}

function toString(param) {
  return "<" + (String(param[0]) + ("." + (String(param[1]) + ("." + (String(param[2]) + ">")))));
}

var Pid = /* module */[
  /* make */make,
  /* toString */toString
];

function toString$1(param) {
  if (param) {
    return "dead";
  } else {
    return "alive";
  }
}

var Status = /* module */[/* toString */toString$1];

function markAsDead(p) {
  p[/* status */1][0] = /* Dead */1;
  return /* () */0;
}

function keepAlive(p) {
  p[/* status */1][0] = /* Alive */0;
  return /* () */0;
}

function send(msg, $$process) {
  $$process[/* mailbox */2][0] = List.append($$process[/* mailbox */2][0], /* :: */[
        msg,
        /* [] */0
      ]);
  return /* () */0;
}

function recv($$process, param) {
  var match = $$process[/* mailbox */2][0];
  if (match) {
    $$process[/* mailbox */2][0] = match[1];
    return Js_primitive.some(match[0]);
  }
  
}

function make$1(pid, f, initial_args) {
  var process_001 = /* status : record */[/* contents : Alive */0];
  var process_002 = /* mailbox : record */[/* contents : [] */0];
  var $$process = /* record */[
    /* pid */pid,
    process_001,
    process_002
  ];
  var env = [];
  var run = function (args) {
    var exit = 0;
    var val;
    try {
      val = Curry._2(f, env, args);
      exit = 1;
    }
    catch (raw_ex){
      var ex = Js_exn.internalToOCamlException(raw_ex);
      console.log("Process Terminated: " + (String($$process) + (" threw " + (String(ex) + ""))));
      process_001[0] = /* Dead */1;
      return /* () */0;
    }
    if (exit === 1) {
      if (typeof val === "number") {
        process_001[0] = /* Dead */1;
        return /* () */0;
      } else {
        switch (val.tag | 0) {
          case 0 : 
              var newState = val[0];
              return ReActor_Runtime.nextTick((function (param) {
                            return run(newState);
                          }));
          case 1 : 
              var newState$1 = val[0];
              return ReActor_Runtime.onAnimationFrame((function (param) {
                            return run(newState$1);
                          }));
          case 2 : 
              var newState$2 = val[1];
              return ReActor_Runtime.defer((function (param) {
                            return run(newState$2);
                          }), val[0]);
          
        }
      }
    }
    
  };
  Caml_obj.caml_update_dummy(env, /* record */[
        /* self */(function (param) {
            return pid;
          }),
        /* recv */(function (param) {
            return recv($$process, param);
          })
      ]);
  run(initial_args);
  return $$process;
}

exports.Message = Message;
exports.Pid = Pid;
exports.Status = Status;
exports.markAsDead = markAsDead;
exports.keepAlive = keepAlive;
exports.send = send;
exports.recv = recv;
exports.make = make$1;
/* ReActor_Runtime Not a pure module */
