// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function trace(tracer, pid, message) {
  var match = Curry._2(tracer[/* matcher */0], pid, message);
  if (match) {
    return Curry._1(tracer[/* handler */1], message);
  } else {
    return /* () */0;
  }
}

exports.trace = trace;
/* No side effect */
