// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Block from "../../../node_modules/bs-platform/lib/es6/block.js";
import * as Curry from "../../../node_modules/bs-platform/lib/es6/curry.js";
import * as ReActor from "../src/ReActor.bs.js";
import * as Js_primitive from "../../../node_modules/bs-platform/lib/es6/js_primitive.js";
import * as ReActor_Utils from "../src/ReActor_Utils.bs.js";
import * as Caml_exceptions from "../../../node_modules/bs-platform/lib/es6/caml_exceptions.js";

var __name = "logger";

var Log = Caml_exceptions.create("E3_CollaboratingProcesses.Logger.Log");

function logger_f(env, prefix) {
  var match = Curry._1(env[/* recv */1], /* () */0);
  if (match !== undefined) {
    var m = Js_primitive.valFromOption(match);
    if (m[0] === Log) {
      var n = m[1];
      var diff = ReActor_Utils.Performance[/* now */0](/* () */0) - n | 0;
      console.log("" + (String(prefix) + (" - " + (String(n) + (" (took " + (String(diff) + " ms)"))))));
    }
    
  }
  return /* Become */Block.__(0, [prefix]);
}

var logger = ReActor.register(__name, ReActor.spawn(logger_f, "Default =>"));

var Logger = /* module */[
  /* __name */__name,
  /* Log */Log,
  /* logger_f */logger_f,
  /* logger */logger
];

function clock_f(_, state) {
  ReActor.send(state[/* send_to */1], [
        Log,
        ReActor_Utils.Performance[/* now */0](/* () */0)
      ]);
  return /* Suspend */Block.__(2, [
            state[/* delay */0],
            state
          ]);
}

function start(param) {
  return ReActor.spawn(clock_f, param);
}

var Clock = /* module */[
  /* clock_f */clock_f,
  /* start */start
];

var match = ReActor.whereIs("logger");

if (match !== undefined) {
  ReActor.spawn(clock_f, /* record */[
        /* delay */0,
        /* send_to */match
      ]);
} else {
  console.log("Failed to start logger.");
}

export {
  Logger ,
  Clock ,
  
}
/* logger Not a pure module */
