// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Curry from "../../../node_modules/bs-platform/lib/es6/curry.js";
import * as Caml_exceptions from "../../../node_modules/bs-platform/lib/es6/caml_exceptions.js";
import * as ReActor$Reactor from "../src/ReActor.bs.js";
import * as FFI_Runtime$Reactor from "../src/FFI_Runtime.bs.js";
import * as ReActor_Utils$Reactor from "../src/ReActor_Utils.bs.js";

var Log = Caml_exceptions.create("TestModule_2-Reactor.Log");

function logger_f(env, prefix) {
  Curry._1(env[/* recv */3], (function (m) {
          var now = ReActor_Utils$Reactor.$$Date[/* now */0](/* () */0);
          if (m[0] === Log) {
            console.log("" + (String(prefix) + (" - " + (String(now) + (" - " + (String(m[1]) + ""))))));
          }
          return Curry._1(env[/* loop */0], prefix);
        }));
  return prefix;
}

var logger = ReActor$Reactor.register("logger", ReActor$Reactor.spawn(logger_f, "Default =>"));

console.log("What!");

FFI_Runtime$Reactor.defer((function () {
        return ReActor$Reactor.send(logger, [
                    Log,
                    1
                  ]);
      }), 0);

FFI_Runtime$Reactor.defer((function () {
        return ReActor$Reactor.send(logger, [
                    Log,
                    2
                  ]);
      }), 500);

FFI_Runtime$Reactor.defer((function () {
        return ReActor$Reactor.send(logger, [
                    Log,
                    3
                  ]);
      }), 1000);

FFI_Runtime$Reactor.defer((function () {
        return ReActor$Reactor.send(logger, [
                    Log,
                    4
                  ]);
      }), 3000);

export {
  Log ,
  logger_f ,
  logger ,
  
}
/* logger Not a pure module */
